version: 0.2

env:
  variables:
    ECR_REGISTRY: "654654392564.dkr.ecr.us-east-1.amazonaws.com"
    ECR_REPO: "shopk8s"
    AWS_DEFAULT_REGION: "us-east-1"
    CLUSTER_NAME: "eks-shopk8s"

phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - cat image_tag.env
      - export $(cat image_tag.env)
      - echo Deploying image $IMAGE_TAG

  build:
    commands:
      - kubectl set image deployment/shopk8s shopk8s=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
      - kubectl rollout status deployment/shopk8s --timeout=120s

  post_build:
    commands:
      - echo Deployment completed on `date`
      - kubectl get pods -l app=shopk8s
      - kubectl get svc shopk8s
